---
title: "Eviatar Guttman"
---

I am an economist and data scientist working in the Research department of the [Israeli Competition Authority](https://www.gov.il/en/departments/competition/govil-landing-page) (ICA). I have a passion for working with data and this website showcases some of the code that I have created while working at the ICA.

::: {.callout-warning icon="false"}
## disclaimer

Please note that the opinions expressed on this website are my own and do not necessarily reflect the views of the Israel Competition Authority.
:::

1.  In a research project titled [Information problems in the mortgage market in Israel: price dispersion and search](https://www.gov.il/he/departments/publications/reports/mortgagemarket-final) (unfortunately, the full paper was only published in Hebrew, but there is an extended abstract in English available [here](mortgage_data/Information%20Asymmetry%20and%20the%20Gains%20from%20Shopping%20Evidence%20from%20the%20Israeli%20Mortgage%20Market.pdf)) we made predictions of the entire counter-factual price distribution of mortgage loans if customers had requested more bank bids in a friction-less environment.The example [code](1_mortgage.qmd) provided illustrates the core idea behind this analysis.

2.  Merger simulation is a cutting-edge technique used by competition authorities to predict the impact of mergers on market prices, and it is based on economic models grounded in industrial organization theory.The examples on this site demonstrate some of the predominant techniques used in merger simulation implementation. We provide some [background](2_merger_sim_intro.qmd) information, a [simplified example](3_multinomial_logit.qmd) for clarity, and a more advanced [example](4_nested.qmd) with production-level code.

    I plan to add more examples in the future as time allows. Please feel free to contact me at [**eviatargu\@competition.gov.il**](mailto:eviatargu@competition.gov.il) if you have any questions or comments.
